### ISSUE TITLE
Feature Request:  Environment 

### ISSUE THREAD

**Issue by TechCowboy** [ByteProject/Puny-BuildTools#10]
Documentation and/or workflow change suggestion.

For those developing using Windows/WSL2, system is excellent, however, for those who use Linux (Ubuntu), and don't want their environment 'polluted', may I suggest a change.

Have the environment variables you want to change in it's own script (env.sh) 
```
# add directories to path
export PATH="$HOME/FictionTools:$PATH"
export PATH="$HOME/FictionTools/amitools/bin:$PATH"
export PATH="$HOME/FictionTools/hfsutils:$PATH"
export PATH="$HOME/FictionTools/z88dk/bin:$PATH"
export PATH="$HOME/FictionTools/z88dk/lib:$PATH"
export PATH="/sbin:$PATH"
export ZCCCFG="$HOME/FictionTools/z88dk/lib/config"
```

and invoke it like this:

```
. ./env.sh
```

**Comment by ByteProject** [comment]
Thank you very much for your suggestion. I am not sure whether I would consider this as "polluting" the system. When I started the BuildTools, I was solely working under Linux (under a real Linux) and I had many of these tools at path anyway as they are handy when manipulating disk images or converting pixel art to a format readable to a specific retro host, indeed also out of a BuildTools context. I am a Linux user by heart, in fact only my desktop workhorse runs Windows / WSL2. I had to switch due to my music production endeavours but my Notebook is a fully featured Ubuntu Linux system. And I personally wouldn't consider adding above directories at path as polluting the Linux host. The benefit of the BuildTools is not only being able to build your Inform game for massive load of retro systems, it also is about having all these great tools at your fingertips in any Terminal and in any context you may need them.

I am currently working on version 2.0 of the BuildTools, which will come with significant changes to the architecture for the first time, including a centralized location for the interpreters and a single config file in the actual build directory being all you need. I will definitely think about your suggestion but for the moment I don't think it is desirable. It simply is not practical having something like the Inform compiler not at path when you want to do a quick test without building a disk image or using the PUNY commandline tool I created without putting the story file on an actual retro disk image, e.g. for tests. But I may let the user decide as I am planning an installer for BuildTools 2.0 as well. As long as I haven't made up my mind and while I am still working on 2.0, I will keep this feature request open :)

**Comment by ByteProject** [comment]
Made up my mind. This feature request won't make it into the BuildTools 2.0. I think having the tools at hand all the time is a feature rather than polluting the environment.
