### ISSUE TITLE
a8bit.sh doesn't work with .z5 files

### ISSUE THREAD

**Issue by TechCowboy** [ByteProject/Puny-BuildTools#12]
Currently the extension is hard coded for .z3 within the a8bit.sh script.
Perhaps the puny script needs to create an environment variable for the extension created?

**Comment by ByteProject** [comment]
.z3 is hardcoded for Atari 8-bit because the Atari 8-bit interpreter cannot handle z5 files. Infocom never released a z5 interpreter for Atari 8-bit. Closing this now as there is unfortunately nothing I can do about this. If you plan to release a game on the Atari 8-bit, you need to make it z3 compatible.

Side-note: There will be a workaround in the future as my friend Shawn Sijnstra created VEZZA, an interpreter that works well under CP/M on the Atari 8-bit.  Instructions for the workaround will come with the BuildTools 2.0 but it will require a FujiNet device to work. So if you plan to target plain A8B hardware, z3 will remain your only choice.

**Comment by ByteProject** [comment]
PS: Please refer to the documentation to learn more about the interpreters and their limitations. Not all interpreters work with z5 and some target systems need different interpreters for z5.
