### ISSUE TITLE
Adding destination directory for game disks

### ISSUE THREAD

**Issue by shift838** [ByteProject/Puny-BuildTools#8]
Maybe there is one that easily configured.  But i was thinking of something in the config.sh file that when Puddle Build Tools compiles and creates the image for the specific system(s) that it deposits that image in a different directory so it does not add all the files to where the scripts are already.

I now this could be done in each .sh file for each system, but how about in the config.sh file so it only has to be done once.

**Comment by ByteProject** [comment]
A fundamental design logic of the BuildTools is that the disk image output happens in the the project's root directory, which is where the scripts are located. My guess is you want the images in a different directory for distribution. In that case you should configure the `bundle.sh` script instead. Its purpose is to create a ZIP file for distribution which is placed on your desktop and `bundle.sh` can be configured to do something with the images after compilation. So that's your first option.

Your second option would waiting for the BuildTools 2.0 which have completely centralized system resources. You still won't be able to define a different directory for image deposit but the scripts and interpreter resources are not located in the Build directory anymore. Only the config.sh file will be.
