### ISSUE TITLE
Not a valid format for atari 8 bit

### ISSUE THREAD

**Issue by shift838** [ByteProject/Puny-BuildTools#9]
I have used your build tools to build a atari 8 bit disk image (.ATR).  It works on emulator like Altirra, but for a real atari it does not work even when mounting it through FujiNet or SIO2PC.

when doing a directory on it it shows:

volume: LiteDOS
Directory: Root

the image will not auto boot on a real atari, but will on Altirra.  I need it to work on a real atari 8 bit system.

**Comment by ByteProject** [comment]
I have no actual idea what you are doing wrong but I can assure you that _you are in fact_ doing something wrong. ATR files created with the BuildTools work perfectly fine on real Atari hardware and they work just great when playing via FujiNet or a SIO2SD device on real hardware. My game Hibernated is even hosted on the official FujiNet server so that you may play it over the internet on real hardware with your FujiNet device. Your post is unfortunately missing essential information, e.g. on which machine are you trying to run it, which SD device are you using (Fuji or SIO2SD, or maybe you have tried both), so that I am not able to understand where the root cause of your problem is but it's definitely not a BuildTools problem. 

I would suggest you seek help in the official Atari forums or on the FujiNet Discord so that someone who knows the Atari 8-bit in an out is able to understand what you are doing wrong and assist with the steps necessary to make your game run. 

PS: Games created with the BuildTools (targeting Infocom's single disk interpreter) NEVER auto-boot. You need to type DOS when the Basic prompt comes up. This is how Infocom designed the interpreter, so you need to take this as is. 

PPS: I have no idea why the volume would say "LiteDOS". LiteDOS is a modern DOS system for old Atari machines, this has nothing to do with the images the BuildTools create. I don't know LiteDOS and I never tried it. Could be that this is where you're doing something wrong. I stick with my suggestion: seek help from someone who knows the Atari 8-bit in and out, for example on the official FujiNet Discord.
